{"uuid": "3b388631-a46a-4282-a5a6-eb03a10cbadb", "children": ["4616ea54-0008-4de3-a987-53aa61559015"], "befores": [{"name": "on_failure", "status": "passed", "start": 1730743166235, "stop": 1730743166235}], "afters": [{"name": "on_failure::0", "status": "broken", "statusDetails": {"message": "AttributeError: 'Function' object has no attribute 'rep_call'\n", "trace": "  File \"C:\\Users\\100964135\\PycharmProjects\\clockTestCase\\.venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\100964135\\PycharmProjects\\clockTestCase\\.venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 907, in _teardown_yield_fixture\n    next(it)\n    ~~~~^^^^\n  File \"C:\\Users\\100964135\\Desktop\\hevy\\TestCases\\conftest.py\", line 45, in on_failure\n    if item.rep_call.failed:\n       ^^^^^^^^^^^^^\n"}, "start": 1730743176684, "stop": 1730743176700}], "start": 1730743166235, "stop": 1730743176700}