[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DFB82B7E10>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DFB8359C70>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001DFB82E7F00>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session